[project]
name = "Sherpa"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Luis Carlos Quesada", email = "luiscarlosquesada@icloud.com"},
]
dependencies = ["uvicorn>=0.35.0", "fastapi>=0.115.14", "pydantic>=2.11.7"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
